#!/usr/bin/env python3
"""Gemini Spark task queue and synthesis runner.

This daemon synthesizes artifacts. It does not claim physical, C17, competitor-census,
or numerical verification unless a separate verifier actually runs and produces evidence.
Local paths are configurable so repository users are not bound to one workstation.

The daemon never performs Git commits. Repository promotion is intentionally delegated to
an external controller or maintainer so generated artifacts cannot bypass protected-branch
review by inheriting an ambient checkout target.
"""
import json
import os
import shutil
import sqlite3
import hashlib
import time
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(os.environ.get("SOVEREIGN_COMMONS_ROOT", Path(__file__).resolve().parents[1]))
AIR1_HOME = Path(os.environ.get("AIR1_HOME", Path.home() / ".air1"))
QUEUE_DIR = REPO_ROOT / "tasks" / "queue"
IN_PROGRESS_DIR = REPO_ROOT / "tasks" / "in_progress"
COMPLETED_DIR = REPO_ROOT / "tasks" / "completed"
RESEARCH_DIR = REPO_ROOT / "research" / "interconnections"
SPARK_DB = Path(os.environ.get("SPARK_TRANSACTION_DB", AIR1_HOME / "SPARK5_TRANSACTION_LEDGER.sqlite"))
POOL_DB = Path(os.environ.get("WORKSPACE_POOL_DB", AIR1_HOME / "state" / "MULTI_ACCOUNT_WORKSPACE_POOL.sqlite"))
RECEIPT_DIR = Path(os.environ.get("AIR1_RECEIPT_DIR", AIR1_HOME / "receipts"))


def ensure_directories():
    for directory in [QUEUE_DIR, IN_PROGRESS_DIR, COMPLETED_DIR, RESEARCH_DIR]:
        directory.mkdir(parents=True, exist_ok=True)


def record_transaction(task_id: str, effect_id: str, object_id: str, result: str, receipt_path: str):
    if not SPARK_DB.exists():
        return
    try:
        conn = sqlite3.connect(str(SPARK_DB))
        cursor = conn.cursor()
        now = datetime.now(timezone.utc).isoformat()
        cursor.execute(
            """
            INSERT OR REPLACE INTO transactions
            (task_id, effect_id, account_id, service, object_id, started_at, committed_at, verifier, result, retry_condition, receipt_path)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (task_id, effect_id, "rajon369963-del", "gemini-spark", object_id, now, now,
             "UNVERIFIED", result, "INDEPENDENT_VERIFICATION_REQUIRED", receipt_path),
        )
        conn.commit()
        conn.close()
    except Exception as exc:
        print(f"[WARN] Error recording to SPARK DB: {exc}")


def solve_task(task_path: Path) -> Path:
    task_name = task_path.stem
    print(f"[*] Claiming task: {task_name}")
    in_progress_path = IN_PROGRESS_DIR / f"{task_name}_SPARK2.md"
    shutil.move(task_path, in_progress_path)
    task_content = in_progress_path.read_text(encoding="utf-8")
    start_time = time.time()

    solution_text = f"""# SOLUTION DRAFT: {task_name}
> **Processed By**: Gemini Spark Slot 02 (`rajon369963-del`)
> **Timestamp**: {datetime.now(timezone.utc).isoformat()}
> **Verification status**: `SYNTHESIZED_UNVERIFIED`

## 1. Original Objective
{task_content}

## 2. Synthesis
This artifact is a generated synthesis for independent review. It does not assert that a
competitor census, native C17 kernel, hardware acceleration, numerical court, or physical
verification ran. Any such promotion requires a separate executed verifier with command,
input artifact, exit status, assertion result, evidence artifact/hash, timestamp, and verifier ID.

## 3. Receipt
- Status: **SYNTHESIZED_UNVERIFIED**
- Synthesis duration: {(time.time() - start_time) * 1000:.2f} ms
- Producer: `Gemini-Spark-A02`
"""
    solution_path = COMPLETED_DIR / f"{task_name}_SOLUTION.md"
    solution_path.write_text(solution_text, encoding="utf-8")

    sha256 = hashlib.sha256(solution_text.encode("utf-8")).hexdigest()
    RECEIPT_DIR.mkdir(parents=True, exist_ok=True)
    receipt_path = RECEIPT_DIR / f"{task_name}_receipt.json"
    receipt_path.write_text(json.dumps({
        "task_id": task_name,
        "account": "rajon369963-del",
        "artifact_sha256": sha256,
        "status": "SYNTHESIZED_UNVERIFIED",
        "verification": {"executed": False, "verifier_id": None, "evidence": None},
        "promotion": {
            "git_commit_attempted": False,
            "route": "EXTERNAL_CONTROLLER_OR_MAINTAINER_PR",
        },
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }, indent=2), encoding="utf-8")
    record_transaction(task_name, f"EFF-SPARK-{task_name}", str(solution_path),
                       "SYNTHESIZED_UNVERIFIED", str(receipt_path))
    if in_progress_path.exists():
        in_progress_path.unlink()
    print(f"[OK] Synthesized {task_name} -> {solution_path}; independent verification required")
    return solution_path


def generate_hourly_interconnection() -> Path:
    ts = int(time.time())
    inter_path = RESEARCH_DIR / f"INTERCONNECTION_{ts}.md"
    content = f"""# Hourly Research Interconnection #{ts}
> **Generated By**: Gemini Spark Slot 02 (`rajon369963-del`)
> **Timestamp**: {datetime.now(timezone.utc).isoformat()}
> **Status**: `SYNTHESIZED_UNVERIFIED`

## Candidate synthesis
Explore a possible relationship between transformer inrush-current dynamics and synchronous-machine
sub-transient reactance. This is a research hypothesis, not a verified invariant. Validate equations,
assumptions, sources, units, and numerical behavior independently before promotion.
"""
    inter_path.write_text(content, encoding="utf-8")
    record_transaction(f"INTER-{ts}", f"EFF-RESEARCH-{ts}", str(inter_path),
                       "SYNTHESIZED_UNVERIFIED", str(inter_path))
    print(f"[OK] Generated unverified research candidate: {inter_path}")
    return inter_path


def run_cycle():
    ensure_directories()
    pending_tasks = sorted(list(QUEUE_DIR.glob("*.md")) + list(QUEUE_DIR.glob("*.json")))
    if pending_tasks:
        for task in pending_tasks:
            solve_task(task)
    else:
        generate_hourly_interconnection()

    # Intentionally no `git add` or `git commit` here. Generated files remain local artifacts
    # until an external controller/maintainer places them on an explicit work branch and sends
    # them through the repository's normal PR + required-check review path.
    print("[HOLD] Repository promotion delegated to external controller/maintainer PR workflow")

    if POOL_DB.exists():
        try:
            conn = sqlite3.connect(str(POOL_DB))
            cursor = conn.cursor()
            cursor.execute(
                "UPDATE accounts SET last_used_timestamp = ?, total_requests_served = total_requests_served + 1 WHERE slot_number = 2",
                (time.time(),),
            )
            conn.commit()
            conn.close()
        except Exception as exc:
            print(f"[WARN] Error updating pool: {exc}")


if __name__ == "__main__":
    run_cycle()
